// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm --prefix packages/ai run generate-models' to update
// Source: https://api.neosantara.xyz/v1/models
// Includes non-deprecated text models that advertise function_calling for coding-agent tool use.
// Costs are normalized to IDR per million tokens to match Neosantara billing.

import type { Api, Model } from "./types.js";

const NEOSANTARA_BASE_URL = "https://api.neosantara.xyz/v1";

function neosantaraModel(
	id: string,
	name: string,
	options: Partial<Model<"openai-responses">> = {},
): Model<"openai-responses"> {
	return {
		id,
		name,
		api: "openai-responses",
		provider: "neosantara",
		baseUrl: NEOSANTARA_BASE_URL,
		reasoning: options.reasoning ?? false,
		input: options.input ?? ["text", "image"],
		cost: options.cost ?? { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		costCurrency: options.costCurrency ?? "IDR",
		contextWindow: options.contextWindow ?? 131072,
		maxTokens: options.maxTokens ?? 32000,
		compat: {
			sendSessionIdHeader: false,
			supportsLongCacheRetention: false,
			...options.compat,
		},
	};
}

export const MODELS = {
	neosantara: {
		"amazon-nova-lite": neosantaraModel("amazon-nova-lite", "amazon-nova-lite", { contextWindow: 300000, maxTokens: 4096, cost: { input: 1038.146076, output: 4152.584304, cacheRead: 0, cacheWrite: 0 } }),
		"amazon-nova-micro": neosantaraModel("amazon-nova-micro", "amazon-nova-micro", { input: ["text"], contextWindow: 300000, maxTokens: 4096, cost: { input: 605.585211, output: 2422.340844, cacheRead: 0, cacheWrite: 0 } }),
		"amazon-nova-pro": neosantaraModel("amazon-nova-pro", "amazon-nova-pro", { contextWindow: 300000, maxTokens: 4096, cost: { input: 13841.94768, output: 55367.79072, cacheRead: 0, cacheWrite: 0 } }),
		"apriel-1.6-thinker": neosantaraModel("apriel-1.6-thinker", "apriel-1.6-thinker", { reasoning: true, input: ["text"], contextWindow: 32768, maxTokens: 4096, cost: { input: 3000, output: 9000, cacheRead: 0, cacheWrite: 0 } }),
		"claude-4-5-haiku": neosantaraModel("claude-4-5-haiku", "claude-4-5-haiku", { reasoning: true, contextWindow: 200000, maxTokens: 8192, cost: { input: 17302.4346, output: 86512.173, cacheRead: 1730.24346, cacheWrite: 21628.04325 } }),
		"claude-4.5-haiku": neosantaraModel("claude-4.5-haiku", "claude-4.5-haiku", { contextWindow: 200000, maxTokens: 4096, cost: { input: 17302.4346, output: 86512.173, cacheRead: 1730.24346, cacheWrite: 21628.04325 } }),
		"claude-4.5-opus": neosantaraModel("claude-4.5-opus", "claude-4.5-opus", { contextWindow: 200000, maxTokens: 4096, cost: { input: 86512.173, output: 432560.865, cacheRead: 8651.2173, cacheWrite: 108140.21625 } }),
		"claude-4.5-sonnet": neosantaraModel("claude-4.5-sonnet", "claude-4.5-sonnet", { contextWindow: 200000, maxTokens: 4096, cost: { input: 51907.3038, output: 259536.519, cacheRead: 5190.73038, cacheWrite: 64884.12975 } }),
		"claude-opus-4-6": neosantaraModel("claude-opus-4-6", "claude-opus-4-6", { reasoning: true, input: ["text"], contextWindow: 200000, maxTokens: 8192, cost: { input: 86512.173, output: 432560.865, cacheRead: 8651.2173, cacheWrite: 108140.21625 } }),
		"claude-sonnet-4-6": neosantaraModel("claude-sonnet-4-6", "claude-sonnet-4-6", { reasoning: true, input: ["text"], contextWindow: 200000, maxTokens: 8192, cost: { input: 51907.3038, output: 259536.519, cacheRead: 5190.73038, cacheWrite: 64884.12975 } }),
		"deepseek-v4-flash": neosantaraModel("deepseek-v4-flash", "deepseek-v4-flash", { reasoning: true, contextWindow: 1000000, maxTokens: 4096, cost: { input: 2422.340844, output: 4844.681688, cacheRead: 48.446817, cacheWrite: 0 }, compat: { supportsReasoningWithTools: false } }),
		"deepseek-v4-pro": neosantaraModel("deepseek-v4-pro", "deepseek-v4-pro", { reasoning: true, contextWindow: 1000000, maxTokens: 4096, cost: { input: 30106.236204, output: 60212.472408, cacheRead: 250.885302, cacheWrite: 0 }, compat: { supportsReasoningWithTools: false } }),
		"devstral-2": neosantaraModel("devstral-2", "devstral-2", { input: ["text"], contextWindow: 128000, maxTokens: 4096 }),
		"garda-core": neosantaraModel("garda-core", "garda-core", { contextWindow: 64000, maxTokens: 2048, cost: { input: 300, output: 1500, cacheRead: 0, cacheWrite: 0 } }),
		"gemini-2.5-flash": neosantaraModel("gemini-2.5-flash", "gemini-2.5-flash", { reasoning: true, input: ["text"], contextWindow: 65536, maxTokens: 4096, cost: { input: 5253, output: 43779, cacheRead: 525, cacheWrite: 5253 } }),
		"gemini-3-flash": neosantaraModel("gemini-3-flash", "gemini-3-flash", { contextWindow: 1000000, maxTokens: 2400, cost: { input: 8651.2173, output: 51907.3038, cacheRead: 1730.24346, cacheWrite: 519.073038 } }),
		"gemini-3-flash-preview": neosantaraModel("gemini-3-flash-preview", "gemini-3-flash-preview", { reasoning: true, contextWindow: 1000000, maxTokens: 8192, cost: { input: 1600, output: 6400, cacheRead: 0, cacheWrite: 0 } }),
		"gemini-3-pro-preview": neosantaraModel("gemini-3-pro-preview", "gemini-3-pro-preview", { contextWindow: 128000, maxTokens: 8192, cost: { input: 40000, output: 120000, cacheRead: 0, cacheWrite: 0 } }),
		"gemini-3.1-flash-lite-preview": neosantaraModel("gemini-3.1-flash-lite-preview", "gemini-3.1-flash-lite-preview", { contextWindow: 1000000, maxTokens: 8192, cost: { input: 1600, output: 6400, cacheRead: 0, cacheWrite: 0 } }),
		"gemini-3.1-pro-preview": neosantaraModel("gemini-3.1-pro-preview", "gemini-3.1-pro-preview", { contextWindow: 128000, maxTokens: 8192, cost: { input: 40000, output: 120000, cacheRead: 0, cacheWrite: 0 } }),
		"gemma-3-27b-it": neosantaraModel("gemma-3-27b-it", "gemma-3-27b-it", { input: ["text"], contextWindow: 32768, maxTokens: 4096, cost: { input: 200, output: 1500, cacheRead: 0, cacheWrite: 0 } }),
		"glm-4.5-flash": neosantaraModel("glm-4.5-flash", "glm-4.5-flash", { contextWindow: 128000, maxTokens: 8192, cost: { input: 250, output: 750, cacheRead: 0, cacheWrite: 0 } }),
		"glm-4.6v-flash": neosantaraModel("glm-4.6v-flash", "glm-4.6v-flash", { reasoning: true, contextWindow: 128000, maxTokens: 8192, cost: { input: 250, output: 750, cacheRead: 0, cacheWrite: 0 } }),
		"glm-4.7": neosantaraModel("glm-4.7", "glm-4.7", { contextWindow: 128000, maxTokens: 8192, cost: { input: 10000, output: 30000, cacheRead: 0, cacheWrite: 0 } }),
		"glm-4.7-flash": neosantaraModel("glm-4.7-flash", "glm-4.7-flash", { input: ["text"], contextWindow: 1000000, maxTokens: 8192 }),
		"gpt-5-nano": neosantaraModel("gpt-5-nano", "gpt-5-nano", { reasoning: true, contextWindow: 128000, maxTokens: 4096, cost: { input: 810, output: 6485, cacheRead: 0, cacheWrite: 0 } }),
		"gpt-5.4-nano": neosantaraModel("gpt-5.4-nano", "gpt-5.4-nano", { reasoning: true, contextWindow: 400000, maxTokens: 4096, cost: { input: 3240, output: 20250, cacheRead: 0, cacheWrite: 0 } }),
		"gpt-oss-20b": neosantaraModel("gpt-oss-20b", "gpt-oss-20b", { input: ["text"], maxTokens: 8192, cost: { input: 400, output: 1600, cacheRead: 0, cacheWrite: 0 } }),
		"granite-3-8b-instruct": neosantaraModel("granite-3-8b-instruct", "granite-3-8b-instruct", { input: ["text"], contextWindow: 128000, maxTokens: 2048, cost: { input: 2880, output: 11520, cacheRead: 0, cacheWrite: 0 } }),
		"grok-4.1-fast-non-reasoning": neosantaraModel("grok-4.1-fast-non-reasoning", "grok-4.1-fast-non-reasoning", { input: ["text"], contextWindow: 2000000, maxTokens: 4096, cost: { input: 5190.73038, output: 12457.752912, cacheRead: 1730.24346, cacheWrite: 2595.36519 } }),
		"grok-4.1-fast-reasoning": neosantaraModel("grok-4.1-fast-reasoning", "grok-4.1-fast-reasoning", { reasoning: true, input: ["text"], contextWindow: 2000000, maxTokens: 4096, cost: { input: 5190.73038, output: 12457.752912, cacheRead: 1730.24346, cacheWrite: 2595.36519 } }),
		"grok-4.3": neosantaraModel("grok-4.3", "grok-4.3", { reasoning: true, contextWindow: 1000000, maxTokens: 4096, cost: { input: 21628.04325, output: 43256.0865, cacheRead: 3460.48692, cacheWrite: 0 } }),
		"grok-code-fast": neosantaraModel("grok-code-fast", "grok-code-fast", { input: ["text"], contextWindow: 256000, maxTokens: 4096, cost: { input: 3460.48692, output: 25953.6519, cacheRead: 865.12173, cacheWrite: 2249.316498 } }),
		"hermes-2-pro-mistral-7b": neosantaraModel("hermes-2-pro-mistral-7b", "hermes-2-pro-mistral-7b", { input: ["text"], contextWindow: 24000, maxTokens: 4096, cost: { input: 450, output: 1200, cacheRead: 0, cacheWrite: 0 } }),
		"kimi-k2-thinking": neosantaraModel("kimi-k2-thinking", "kimi-k2-thinking", { reasoning: true, input: ["text"], contextWindow: 128000, maxTokens: 16384, cost: { input: 10381.46076, output: 43256.0865, cacheRead: 0, cacheWrite: 0 } }),
		"kimi-k2.5": neosantaraModel("kimi-k2.5", "kimi-k2.5", { reasoning: true, contextWindow: 256000, maxTokens: 16384, cost: { input: 10381.46076, output: 51907.3038, cacheRead: 0, cacheWrite: 0 } }),
		"llama-3-2-11b-vision": neosantaraModel("llama-3-2-11b-vision", "llama-3-2-11b-vision", { contextWindow: 128000, maxTokens: 4096, cost: { input: 2768.389536, output: 2768.389536, cacheRead: 0, cacheWrite: 0 } }),
		"llama-3.3-nemotron-super-49b-v1.5": neosantaraModel("llama-3.3-nemotron-super-49b-v1.5", "llama-3.3-nemotron-super-49b-v1.5", { input: ["text"], contextWindow: 132000, maxTokens: 128000, cost: { input: 4560, output: 31991, cacheRead: 0, cacheWrite: 0 } }),
		"longcat-flash-thinking": neosantaraModel("longcat-flash-thinking", "longcat-flash-thinking", { reasoning: true, input: ["text"], contextWindow: 33000, maxTokens: 4096 }),
		"mistral-large-latest": neosantaraModel("mistral-large-latest", "mistral-large-latest", { input: ["text"], contextWindow: 128000, maxTokens: 8192, cost: { input: 8651.2173, output: 25953.6519, cacheRead: 0, cacheWrite: 0 } }),
		"mistral-small-latest": neosantaraModel("mistral-small-latest", "mistral-small-latest", { input: ["text"], contextWindow: 128000, maxTokens: 4096, cost: { input: 2595.36519, output: 10381.46076, cacheRead: 0, cacheWrite: 0 } }),
		"qwen3-32b": neosantaraModel("qwen3-32b", "qwen3-32b", { input: ["text"], maxTokens: 40960, cost: { input: 4828, output: 9823, cacheRead: 0, cacheWrite: 0 } }),
		"step-3.5-flash": neosantaraModel("step-3.5-flash", "step-3.5-flash", { reasoning: true, input: ["text"], contextWindow: 256000, maxTokens: 16384, cost: { input: 3000, output: 9000, cacheRead: 0, cacheWrite: 0 } }),
	},
} as const satisfies Record<string, Record<string, Model<Api>>>;
