#!/usr/bin/env node

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type JsonRecord = Record<string, unknown>;
type ModelInput = "text" | "image";

interface GeneratedModelEntry {
	id: string;
	name: string;
	reasoning: boolean;
	input: ModelInput[];
	contextWindow: number;
	maxTokens: number;
	currency: string;
	pricing: {
		prompt: number;
		completion: number;
		cacheRead: number;
		cacheWrite: number;
	};
	costCurrency: "IDR";
	cost: {
		input: number;
		output: number;
		cacheRead: number;
		cacheWrite: number;
	};
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, "..");

const MODELS_URL = "https://api.neosantara.xyz/v1/models";
const EXCHANGE_RATE_URL = "https://api.neosantara.xyz/v1/public/exchange-rate";
const MODELS_OUTPUT_PATH = join(packageRoot, "src/models.generated.ts");
const FALLBACK_USD_TO_IDR = 16650;

function isRecord(value: unknown): value is JsonRecord {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readArray(value: unknown): string[] {
	return Array.isArray(value) ? value : [];
}

function readNumber(value: unknown, fallback: number): number {
	return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

function roundRate(value: number): number {
	return Number(value.toFixed(6));
}

function isCodingAgentModel(model: JsonRecord): boolean {
	const capabilities = readArray(model.capabilities);
	return (
		model.deprecated !== true &&
		capabilities.includes("text_generation") &&
		capabilities.includes("function_calling")
	);
}

function toModelEntry(model: JsonRecord): Omit<GeneratedModelEntry, "cost" | "costCurrency"> {
	const capabilities = readArray(model.capabilities);
	const pricing = isRecord(model.pricing) ? model.pricing : {};
	const currency = typeof pricing.currency === "string" && pricing.currency.trim() ? pricing.currency : "IDR";
	return {
		id: String(model.id),
		name: String(model.id),
		reasoning: capabilities.includes("reasoning"),
		input: capabilities.includes("vision") ? ["text", "image"] : ["text"],
		contextWindow: readNumber(model.context_window, 131072),
		maxTokens: readNumber(model.max_output_tokens, 32000),
		currency,
		pricing: {
			prompt: readNumber(pricing.prompt, 0),
			completion: readNumber(pricing.completion, 0),
			cacheRead: readNumber(pricing.cache_read, 0),
			cacheWrite: readNumber(pricing.cache_write, 0),
		},
	};
}

function buildModelLines(model: GeneratedModelEntry): string {
	const options: string[] = [];

	if (model.reasoning) {
		options.push("reasoning: true");
	}
	if (model.input.length !== 2 || model.input[1] !== "image") {
		options.push(`input: [${model.input.map((value) => JSON.stringify(value)).join(", ")}]`);
	}
	if (model.contextWindow !== 131072) {
		options.push(`contextWindow: ${model.contextWindow}`);
	}
	if (model.maxTokens !== 32000) {
		options.push(`maxTokens: ${model.maxTokens}`);
	}
	if (
		model.cost.input !== 0 ||
		model.cost.output !== 0 ||
		model.cost.cacheRead !== 0 ||
		model.cost.cacheWrite !== 0
	) {
		options.push(
			`cost: { input: ${model.cost.input}, output: ${model.cost.output}, cacheRead: ${model.cost.cacheRead}, cacheWrite: ${model.cost.cacheWrite} }`,
		);
	}
	if (model.costCurrency !== "IDR") {
		options.push(`costCurrency: ${JSON.stringify(model.costCurrency)}`);
	}

	const optionsSuffix = options.length > 0 ? `, { ${options.join(", ")} }` : "";
	return `\t\t${JSON.stringify(model.id)}: neosantaraModel(${JSON.stringify(model.id)}, ${JSON.stringify(model.name)}${optionsSuffix}),`;
}

function generateModelsFile(models: GeneratedModelEntry[]): string {
	const lines = [
		"// This file is auto-generated by scripts/generate-models.ts",
		"// Do not edit manually - run 'npm --prefix packages/ai run generate-models' to update",
		"// Source: https://api.neosantara.xyz/v1/models",
		"// Includes non-deprecated text models that advertise function_calling for coding-agent tool use.",
		"// Costs are normalized to IDR per million tokens to match Neosantara billing.",
		"",
		"import type { Api, Model } from \"./types.js\";",
		"",
		"const NEOSANTARA_BASE_URL = \"https://api.neosantara.xyz/v1\";",
		"",
		"function neosantaraModel(",
		"\tid: string,",
		"\tname: string,",
		"\toptions: Partial<Model<\"openai-responses\">> = {},",
		"): Model<\"openai-responses\"> {",
		"\treturn {",
		"\t\tid,",
		"\t\tname,",
		"\t\tapi: \"openai-responses\",",
		"\t\tprovider: \"neosantara\",",
		"\t\tbaseUrl: NEOSANTARA_BASE_URL,",
		"\t\treasoning: options.reasoning ?? false,",
		"\t\tinput: options.input ?? [\"text\", \"image\"],",
		"\t\tcost: options.cost ?? { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },",
		"\t\tcostCurrency: options.costCurrency ?? \"IDR\",",
		"\t\tcontextWindow: options.contextWindow ?? 131072,",
		"\t\tmaxTokens: options.maxTokens ?? 32000,",
		"\t\tcompat: {",
		"\t\t\tsendSessionIdHeader: false,",
		"\t\t\tsupportsLongCacheRetention: false,",
		"\t\t\t...options.compat,",
		"\t\t},",
		"\t};",
		"}",
		"",
		"export const MODELS = {",
		"\tneosantara: {",
		...models.map(buildModelLines),
		"\t},",
		"} as const satisfies Record<string, Record<string, Model<Api>>>;",
		"",
	];

	return lines.join("\n");
}

async function fetchModels(): Promise<unknown[]> {
	const response = await fetch(MODELS_URL, {
		headers: {
			Accept: "application/json",
			"User-Agent": "@neosantara-xyz/ai model registry generator",
		},
	});
	if (!response.ok) {
		throw new Error(`Failed to fetch ${MODELS_URL}: ${response.status} ${response.statusText}`);
	}

	const payload = await response.json();
	if (!isRecord(payload) || !Array.isArray(payload.data)) {
		throw new Error("Unexpected response payload from /v1/models");
	}

	return payload.data;
}

async function fetchUsdToIdrRate(): Promise<number> {
	try {
		const response = await fetch(EXCHANGE_RATE_URL, {
			headers: {
				Accept: "application/json",
				"User-Agent": "@neosantara-xyz/ai model registry generator",
			},
		});
		if (!response.ok) {
			return FALLBACK_USD_TO_IDR;
		}
		const payload = await response.json();
		const rate = isRecord(payload) && isRecord(payload.data) ? readNumber(payload.data.rate, FALLBACK_USD_TO_IDR) : FALLBACK_USD_TO_IDR;
		return rate > 0 ? rate : FALLBACK_USD_TO_IDR;
	} catch {
		return FALLBACK_USD_TO_IDR;
	}
}

async function main(): Promise<void> {
	const rawModels = await fetchModels();
	const usdToIdrRate = await fetchUsdToIdrRate();
	const dedupedModels = new Map<string, GeneratedModelEntry>();
	for (const rawModel of rawModels) {
		if (!isRecord(rawModel) || !isCodingAgentModel(rawModel)) {
			continue;
		}
		const entry = toModelEntry(rawModel);
		const multiplier = entry.currency === "USD" ? usdToIdrRate : 1;
		dedupedModels.set(entry.id, {
			...entry,
			costCurrency: "IDR",
			cost: {
			input: roundRate(entry.pricing.prompt * multiplier),
			output: roundRate(entry.pricing.completion * multiplier),
			cacheRead: roundRate(entry.pricing.cacheRead * multiplier),
			cacheWrite: roundRate(entry.pricing.cacheWrite * multiplier),
			},
		});
	}

	const textModels = [...dedupedModels.values()].sort((left, right) => left.id.localeCompare(right.id));

	writeFileSync(MODELS_OUTPUT_PATH, generateModelsFile(textModels));
	console.log(`Generated ${MODELS_OUTPUT_PATH}`);
	console.log(`Included ${textModels.length} non-deprecated tool-capable text/chat models from ${MODELS_URL}`);
	console.log(`Normalized pricing to IDR using USD/IDR rate ${usdToIdrRate}`);
}

main().catch((error) => {
	console.error(error instanceof Error ? error.message : String(error));
	process.exitCode = 1;
});
